{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConnectionError"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/pulse\/remotelogger\/connectionerror"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.github.pulse\/10Foundation14LocalizedErrorP","doc:\/\/com.github.pulse\/s5ErrorP","doc:\/\/com.github.pulse\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/network(_:)","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/unknown(isProtected:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/errorDescription"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/Error-Implementations","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/LocalizedError-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConnectionError"}],"title":"RemoteLogger.ConnectionError","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"s:5Pulse12RemoteLoggerC15ConnectionErrorO","modules":[{"name":"Pulse"}],"navigatorTitle":[{"kind":"identifier","text":"ConnectionError"}]},"hierarchy":{"paths":[["doc:\/\/com.github.pulse\/documentation\/Pulse","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger"]]},"references":{"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/LocalizedError-Implementations":{"role":"collectionGroup","title":"LocalizedError Implementations","abstract":[],"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/LocalizedError-Implementations","kind":"article","type":"topic","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/localizederror-implementations"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/network(_:)":{"role":"symbol","title":"RemoteLogger.ConnectionError.network(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"network"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NWError","preciseIdentifier":"s:7Network7NWErrorO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/network(_:)","kind":"symbol","type":"topic","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/network(_:)"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/unknown(isProtected:)":{"role":"symbol","title":"RemoteLogger.ConnectionError.unknown(isProtected:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isProtected"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/unknown(isProtected:)","kind":"symbol","type":"topic","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/unknown(isprotected:)"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/errorDescription":{"role":"symbol","title":"errorDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/errorDescription","kind":"symbol","type":"topic","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/errordescription"},"doc://com.github.pulse/10Foundation14LocalizedErrorP":{"type":"unresolvable","title":"Foundation.LocalizedError","identifier":"doc:\/\/com.github.pulse\/10Foundation14LocalizedErrorP"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/Error-Implementations":{"role":"collectionGroup","title":"Error Implementations","abstract":[],"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/Error-Implementations","kind":"article","type":"topic","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/error-implementations"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger":{"role":"symbol","title":"RemoteLogger","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoteLogger"}],"abstract":[{"type":"text","text":"Connects to the remote server and sends logs remotely. In the current version,"},{"type":"text","text":" "},{"type":"text","text":"a server is a Pulse Pro app for macOS)."}],"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RemoteLogger"}],"url":"\/documentation\/pulse\/remotelogger"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError":{"role":"symbol","title":"RemoteLogger.ConnectionError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConnectionError"}],"abstract":[],"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConnectionError"}],"url":"\/documentation\/pulse\/remotelogger\/connectionerror"},"doc://com.github.pulse/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.github.pulse\/s8SendableP"},"doc://com.github.pulse/documentation/Pulse":{"role":"collection","title":"Pulse","abstract":[{"type":"text","text":"Logger and network inspector for Apple platforms."}],"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse","kind":"symbol","type":"topic","url":"\/documentation\/pulse"},"doc://com.github.pulse/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/com.github.pulse\/s5ErrorP"}}}