{"metadata":{"role":"collectionGroup","modules":[{"name":"Pulse"}],"roleHeading":"API Collection","title":"Error Implementations"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pulse\/remotelogger\/connectionerror\/error-implementations"]}],"kind":"article","identifier":{"url":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/Error-Implementations","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.github.pulse\/documentation\/Pulse","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError"]]},"topicSections":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/localizedDescription"]}],"references":{"doc://com.github.pulse/documentation/Pulse":{"kind":"symbol","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse","url":"\/documentation\/pulse","abstract":[{"type":"text","text":"Logger and network inspector for Apple platforms."}],"type":"topic","title":"Pulse","role":"collection"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger":{"abstract":[{"type":"text","text":"Connects to the remote server and sends logs remotely. In the current version,"},{"type":"text","text":" "},{"text":"a server is a Pulse Pro app for macOS).","type":"text"}],"role":"symbol","url":"\/documentation\/pulse\/remotelogger","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RemoteLogger","kind":"identifier"}],"kind":"symbol","title":"RemoteLogger","navigatorTitle":[{"kind":"identifier","text":"RemoteLogger"}],"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/localizedDescription":{"identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/localizedDescription","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"localizedDescription"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[],"type":"topic","title":"localizedDescription","role":"symbol","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/localizeddescription","kind":"symbol"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError":{"role":"symbol","navigatorTitle":[{"text":"ConnectionError","kind":"identifier"}],"type":"topic","url":"\/documentation\/pulse\/remotelogger\/connectionerror","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConnectionError"}],"title":"RemoteLogger.ConnectionError","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError"}}}