{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pulse\/remotelogger\/connectionerror\/network(_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/network(_:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.github.pulse\/documentation\/Pulse","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger","doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError"]]},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"network"},{"text":"(","kind":"text"},{"text":"NWError","kind":"typeIdentifier","preciseIdentifier":"s:7Network7NWErrorO"},{"text":")","kind":"text"}],"role":"symbol","modules":[{"name":"Pulse"}],"roleHeading":"Case","title":"RemoteLogger.ConnectionError.network(_:)","symbolKind":"case","externalID":"s:5Pulse12RemoteLoggerC15ConnectionErrorO7networkyAE7Network7NWErrorOcAEmF"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"network","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:7Network7NWErrorO","kind":"typeIdentifier","text":"NWError"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.github.pulse/documentation/Pulse/RemoteLogger":{"navigatorTitle":[{"kind":"identifier","text":"RemoteLogger"}],"url":"\/documentation\/pulse\/remotelogger","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RemoteLogger","kind":"identifier"}],"kind":"symbol","title":"RemoteLogger","abstract":[{"type":"text","text":"Connects to the remote server and sends logs remotely. In the current version,"},{"text":" ","type":"text"},{"type":"text","text":"a server is a Pulse Pro app for macOS)."}],"role":"symbol"},"doc://com.github.pulse/documentation/Pulse":{"title":"Pulse","url":"\/documentation\/pulse","abstract":[{"text":"Logger and network inspector for Apple platforms.","type":"text"}],"role":"collection","type":"topic","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse","kind":"symbol"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError/network(_:)":{"kind":"symbol","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError\/network(_:)","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"network"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NWError","preciseIdentifier":"s:7Network7NWErrorO"},{"text":")","kind":"text"}],"title":"RemoteLogger.ConnectionError.network(_:)","url":"\/documentation\/pulse\/remotelogger\/connectionerror\/network(_:)","abstract":[],"type":"topic"},"doc://com.github.pulse/documentation/Pulse/RemoteLogger/ConnectionError":{"navigatorTitle":[{"kind":"identifier","text":"ConnectionError"}],"type":"topic","kind":"symbol","abstract":[],"title":"RemoteLogger.ConnectionError","role":"symbol","identifier":"doc:\/\/com.github.pulse\/documentation\/Pulse\/RemoteLogger\/ConnectionError","url":"\/documentation\/pulse\/remotelogger\/connectionerror","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConnectionError"}]}}}